name: Security Checks

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install safety
        run: pip install safety
      
      - name: Check Python dependencies
        run: |
          # Create requirements files if they don't exist
          touch lambda/inference_handler/requirements.txt
          touch lambda/upload_handler/requirements.txt
          touch tests/requirements.txt
          
          # Install dependencies safely
          if [ -s lambda/inference_handler/requirements.txt ]; then
            pip install -r lambda/inference_handler/requirements.txt
          fi
          if [ -s lambda/upload_handler/requirements.txt ]; then
            pip install -r lambda/upload_handler/requirements.txt
          fi
          if [ -s tests/requirements.txt ]; then
            pip install -r tests/requirements.txt
          fi
          
          # Run safety check
          safety check --json --output safety-report.json --continue-on-error || true
      
      - name: Upload safety report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: safety-report
          path: safety-report.json

  secrets-scan:
    name: Secrets Detection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified --fail

  infrastructure-security:
    name: Infrastructure Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true
          skip_check: CKV_AWS_79,CKV_AWS_116,CKV_AWS_117,CKV_AWS_173
      
      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: checkov-results.sarif

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install pip-licenses
        run: pip install pip-licenses
      
      - name: Check licenses
        run: |
          # Create requirements files if they don't exist
          touch lambda/inference_handler/requirements.txt
          touch lambda/upload_handler/requirements.txt
          
          # Install dependencies safely
          if [ -s lambda/inference_handler/requirements.txt ]; then
            pip install -r lambda/inference_handler/requirements.txt
          fi
          if [ -s lambda/upload_handler/requirements.txt ]; then
            pip install -r lambda/upload_handler/requirements.txt
          fi
          
          # Generate license report
          pip-licenses --format=json --output-file=licenses.json --ignore-packages pip setuptools wheel
      
      - name: Upload license report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: license-report
          path: licenses.json
